---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB2xKQAgLahm7CYBolPSAXCvXT2AKpnBNBl91uYeUqAmKW9Gtsqrgau2RzUBpvQnRnsFWsAqoDY7PBlJ3kvMtTwhS8eqwiaRb7CecWp3naikw1Vaot/DrLhIahr8N40M1pFkFEBOYUW6/YRth91fE5viCRCJQvN3TuiaAY0FfYv8g7jq2G+/suHl1nG7CMgj7XWjuuS/peWKO8ibTFCxw6g1yBbUuZbnwCZWPBNVTRcpvOSCIKUzNpeUZKNcF7ws2xcDv7rwy8KIlWvjuPH06JQDvOnUYAyfhRJW2vMpJDx3XOnlDi0/57gvgl4kQDL4mxb0f0q7/qjR1cDZwtgB4oq1s0lmgE+AIt5YzsEyjfXVGFYNzZkM58bNUALM2TqR+LEJyesHRtBDZunEsWJPkDjdHffZj9Vw5eNoONJGmNqHfTeoX0KrK+faa8LcbcBT8vjFHM19ZBqcZrTALRKX3sB19rlV68BwbwClCzMrvK63l38v50k/U5pcIklizDc+Vy3mQ5B/Cl/1jGcNN78g6IADomkhRJOGBgK6XnnK5HbE0VAQ95kxgsT4canVVEJL2ao7TvZ/WtygY+kTCruy3uYxLCGpIwqDtsyMPefo3zS1+IabCWSDK+k7x94sGRb077ZzV4cHNK92HanlGL1Fu/Q8r94IZep9vppmHkrJk6TvBRnUCpfBcBtZ3lsPLAfk5vCwMjbQynGZ9TU58lf9eTi49WESJB0vvfWS587EKKS6uksQO0n
    admin-user: AgDOiY8Icw2VjdZuLBd5jQLOZWg40H1RAPH9rl8MGFt4Pd1WFsVgBmbpSxP+vyYFimIFV5SAtXWMkVJTuyP5SvvWw+23qHhg4DgL8efkhLsZQGI9WPkgf1MdgbHGqgurS0ZSU/mu8f8N0VYTtN7Y1KPCrwjFM/p3bXXcv8QKaXM3pz2NqsotBH9DS9c0u1cSoDvn58H10zjk52SpUu8nVRvgGk4vtlAMYnbGT0FMSvEJiS65I3tHBayEc994Hvbme037TtHymm7n06pcK2aeouHP3zJquZ3LcxPwwtBnvWEGJgRxwdkmIEb2jESYbEGfrWJWDjDvs4/EFDGi88xPEX9d8JcqFd3Enk64nnJPyjhivzsPFom9pjNxDOqzP5pkPK6i9Am7cJTKMZNpqPsL7jYQElHAKiCr9Ujy1JOnFuVfvWviXT4aLmpBX0768q5gdifAN5RTe7twQ2tUmDekdqDClwobIKGFc3qVil9Ye3PRPD8CEwJ/SBX68mDC8sfBuhyUZS15Pw4BOTZPynpH9FBwIUjonOo2o/ewNyOVrw5sFy1KD4O3Tp7iPfZ26Yo1ucHU/6MkIftWY9Usa/kXFBKvs6p+MK7k047mhe2JrCqkaLkTABy5S+0KeCj3tVgEoVwV+C5CCSaBFnMgssbnB95t+SzWy1MmPWTjiNfqZEhYXGpfLKZyEsPVT/tyDWxQIfor6/E5klln1Xokf8s=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
