---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgApdXynNliYDl6hfStVwi/wAN3zAPA+BwwwlDiqaHxEXP1w7oLhjoPP8PuJcEAL0+GnV4gh+x+wGXU0bdheD8ydIhcFdVtwtfbJhfKr9DmVaA4zkkeKVdwhqAhKSFTbPjm58q7A+InkMOUu9/crv3ulgmO+DD+QY/tNEXv73D6T4js2l2A5b5awrxBoDzPu/oEy3DJpD6nSFhmlTGm/0qCz0Gi19yZhW7DnIEIc9bSvoZIgEdfDFuc6v3DwsahwSRF4XowdFmtsatW0zOYeAMo4SafYi8FbScc0LfON0sGlqpJk8pJLT+tKUgEAsD5X2qzM7Auqlg+8z9mUifEwZdAhPr6hzkTg//yNQ+PXmVHsnRySAUGwUNjRzFvUcR5gNjETxzQWCswbvfP9PlPKYjL1/QRlqgkKUvnRS2sltqE+vhTsO6s4qKjv9iu4xd1F5kssSoBmxo/UTMrlPb4lnzpJxPrv7Y5ZKB0//WeezWKuztEmdcoCcU9JYF46lwqTstGleGIIwACC45nt3H/qginqjAlxPfSlxbJRfzWoVg9U08lcmzJPblc8CkL9gal2pPOr3YYmdZzW20ziMDFUfXodQdGr9fx8ZvrVTZRA3mUolBkvouVqjY/GjHrkY91P2qlQpu7sUDD3FMVraE3y3ax1ZxqO4sC5ENJKZEFgAMtcAyhZs6KXfNht3Lip3MqFI4uCsvsrBm1HP6DHGXLzNI+cYs/4rkcqrN31my48tSe+V1giBUXD
    admin-user: AgBVF+inE60apsDHHwU14uUjwUkczmhxVtHSSVdU+gd4OsWMQffgs3m9nkPDu8927LqLlmOlbcdh7TMP4v8cfmt7MjDs4W09B0F5PO2EAsQHCAUroY7ngY4Kd4N1+JlTMp3oco+AHGs5QRc6nAqr0spYFtRNuvbE8yiZf6fzXW+ynjMINoQ7znZorrFk8FDmaoTb4kKFBoiyPSc9g7bXmfDK2naZIMhyXhhSnCdngxIKi9NemGFgkLOMIkJtwu5F4hdySf/6bRGiXBr/U61Y4HsOv1jXewcouGNkzYmZyI/Zt06zLPzh706Xkhn1p1rj8T0nQ4ilfA79HFzQVgJc2Ey2TzcVqtt+HYJiYwauFfnnIBIJUmhaV1oqamtGOL2YpfAPp7ztQTU6+07uimioEnS5q96yRR2iCCXxfl9YMCUOMFtYLRzq7j5jHBcm+Dh9IDS9ldLCoXsBP+IcImiFldS3usVRy1pJXSmN4Sx2EVt1MfOVpxHlZmTLk3TkFB0mjZVDcYvORA5Rdsg5OHHb5L6AmkwsaEzRQyH26PyKpI+nO6UxC+Aigd41QH2gc6DDze7N6qYaOqVs+VA0VJZ+dJl1GRAifj51Yc0NhV8LcpqQrzh3plR0vMlMDJnM8U4izIN4yc0L1JRK7hBMmGB0nl3clVdtGQ6mz4qW9Tu+87zYda3Uilht5SjAJcLeEecnwILpmZUn+/9yD2S5HNY=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
