---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBs/R7VuMv6QbMpwiBFY8DRR9fIGI6q7xo31w4LQKlxEHCWzaEDxwtSivugEXc/eikru5VRcNEo9FiRaCPIiDEf6d+ApHIB+JcG3nU0AfhMruVXlkOeniU/D71Z8di5SULK2d90sQMgveSTDmN+hDRt/yz+2jW7gLtm447/rlaVGlaxZ7deUBpZsYsRw+w55J0gB/HeTjisQxqzEvv89pzCT+4ZBcAu0HuRMvOOKX5z1Rjvd2pxIaYXsIu6zn48w5meZo5x/M+vQFVnVGD2aFsLFUHAea26yw+F4j54j6TIV2lXaVef/OTihumskEdoWFHvU6k+/4YQ358tHQnvw6ajI7bSvtmgd/xr8ru1PaE0E1gI9xtGRn3p/PlW+nXFyma/mBOiokr4NY/24Rxp+8XZQp+LJI1rUANounRuO7Lvm2Nv3hl5zBmJQpABnHe2ISjMiQ6v78vzMBkQd2LKt7DmmegjSGXoWcU/zD+GLxXPXpau12icojUJKrAg4jR50qq6vyeMa2mH78Ra72nVx5XmLRvMWKJqx3LwRYtcPztP7X4ekcRVbeEjFrs/PjQ8Nd1dW56mHs4IeePFUnjwvUMplnyLmB2copa+MjiBOZg6totoNgkgTUU1pLGpFm0zXR85X8KjJnn/svRa/aSIwo50rY3kWDx43akhIA5/Ur/Ukz4eE3dGD3eqzn3qvsXawLp3l2Jy4p1fYzeX4/3O8Lw/JU+ejCpfLwY=
    admin-user: AgBs2SBVYISk7CKRLNm5qQUvt4gkib4MS/Uc3mnS9u5ABcF+IkJ49l4ybI8mRvsYDJjj5IJmE4TuF6BUI+vkFkwXBp7eT0kSp5Zds6r0BH1GILaVSoNReEamY1NUrJWgiwiGJ2m+3194ezuH96g6gTUo1ZnK1a8JF19GS1Bgc+KEiLhM/gPaYoYQk3I7SAwG9GAshtcQkHsHwjoporxQYavx94xQhlI26l3aS1ExyIV7h2Cleg8s7kr6VbEizqiWQGNjWQjHozIKbqgO3WeX5wHloryH/YecyLNHjw6S5pl9kYdUImv2jbdkPkZq4oQpB4z5yeUmn2PJrk3xy1F1xUL80QdBZrhPlDG2lmAkOtlKbG0MHKaZxmxtE/blJNfEwIVKTPTiLH5dH+ET5qN7000g7X9qq2Jou6W+afkhOf6p8d9nEhYg6Ui0oqHsHeU11Qfn+iOKtnqwEBf+un8R6N1yLQCJAj4VvFfoVxPM8FN+j9jNjJTCB1NE7NoXM5cpBpmh8wFH4R4T+k1DW6xbJT1llzZMIuPoLEpno9fSvmOXx3JySfauCt1Ac3cC33i1+zo1cgxbWNsYFoDxuOJGPxlQAlLjPCthtrZCOlbAuuBrsR3JGyW8PBbkKqA5DkvNkxc25AVVcEavzoJvcUAu0FAxnFbX+m38L6Xrw4jNYwP/YsRtTFbBeVaTAFeNIwdxT5ELK8fGn1uiC+CJSDY=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
