---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xplaceinmyheart-ru
  namespace: default
spec:
  secretName: xplaceinmyheart-ru-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.xplaceinmyheart.ru"
  dnsNames:
    - "xplaceinmyheart.ru"
    - "*.xplaceinmyheart.ru"
