---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgCucr8XKPQs+V3N1utm+bGcmk/AtztjWgUBBA+eDwL2jM7372i8Lq5xvOXHtw1sWZpquI97GdWS0bA4d/uWLMLPde5vinw1mUrmvtXMzPH6En3oSOwUxFLhhYJsIQ+K2JRG9+6/DYti67+WChp7Q6Eri963OHOj0+Wz6WuD1hIkPVbgFgcAWiEMAvCjMfVOZMo5Iynm/r+k4R/qBS1TiQOO8QRowWZdaOYxmLGcXrywdpidMKOsaPxl5LD3J4g8YMLe8WrT8N5rGwGvdt2C8yQJ2QqYhQopvJEV1cyi7wjNteeSAsjrvW+c0rpb91PSEOAhD10AOml71c285mpm5gmieKYEEjTKZzXBWJT+kJYwYZ7ex44IM6D06glBA5ea+oFK8E9DP5xXJKQnTal4TYW9vFC08RttPb04Ld0HK7eDDYbncid6XPt1+V5j8Usth6N5ms09bzQW/3P82d/6oqVK5v819aIEVFe5/aySfUCBXMnH/9iSc/yVNSlZyL76th+sS6AB1XNpjPQLhLJY2PL6DldpWUx34exQuVdDmHGRL479yTWGqor/9oJOKZRy3sRiGpb+4b3xvdpP3aPJzeELyFfAKd/wL8YD8uIGhJXNheldP2yvFB3PpA9+QkLvkj5yHSrZpPHkKe9TPps8H41dZ0K1ZSof2O/zoszQGdWsrRsny7IipET7DNYJKF/kPCvH10itYdIP+kRMR3eh7tPoglbR1jlzMn5i3xda0oVrf5WqaWUT2G5j
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
