---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgAgSOCPD4JeP/2gJJ57QUvX6K+tIjWz9UGUhntS3nx3C9+dknSzwQgUdgxd7b0BM3MA+g90xlmYN1DZYcN2b7Pxq9uhFzhj0QciNle/Y5Zik5Y2kaq2VIg3KLzq2wweWgZ2ybXa/lTT9Xsap0b8IpajX5avRJDOtlcKxzue72UTmt/BMXdzbO/+0T0akkLgjV3eeVncj8cDefR9rtexNhANa0YJi37D/+RAp77MoXqzuONEaR1cBlxgapQ2k1oQqvJDaifMUd6yJ+EplGu4ltsQ1tQV8USnBsnmBo73VMbApGk2P5UiM358cg/2L6qImKF5AIzvM8hheD/n4bM0T0Xr4aC2ltjlu3EBTXQWczFDKX0MQcVcYxA8fh2G3Sa2ApgwEtfYDocRhVFBmDyHTziOZM/t4jLWavDENWs/yxwCmSQvhVtyR2x7SKrEvt6icoNLVIkJ1JgRuCZ8XSib4J/xxaOw+KnJMWImpCfJWfC7+smnMvozc4h3Mf/SOi9E6anpeQz6q+wmY7k+KOiMy6zfDf3JsjMP4dm6Bgh2gSzlDApQJvGwB4q9k7fYy2N7iEMZoJiYbFOXra+oVNptN6VyvlhF0K6qdmx3/kiqKdG79okszaDym5dTXjSiJ5UcYjl5ur2Nuy35e5hZSwTPQ/sx+L7G+JAEdMUszrqEXejQhKiNBftbq3E94M//QB6J8Pmxhjc3fwJ+CjZqe2yWrXH6V2zFpcwyXcNnJxS2Hj15pYKnGESwG1v/
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
