---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xplaceinmyheart-ru
  namespace: istio-ingress
spec:
  secretName: xplaceinmyheart-ru-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.xplaceinmyheart.ru"
  dnsNames:
    - "xplaceinmyheart.ru"
    - "*.xplaceinmyheart.ru"
