---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xplaceinmyheart-ru
  namespace: istio-ingress
spec:
  secretName: xplaceinmyheart-ru-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.xplaceinmyheart.ru"
  dnsNames:
    - "xplaceinmyheart.ru"
    - "*.xplaceinmyheart.ru"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "default,authentik,registry,kafka-development,mongodb-development,postgres-development,redis-development,open-search-development,istio-ingress,dragonflydb-development"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "default,authentik,registry,kafka-development,mongodb-development,postgres-development,redis-development,open-search-development,istio-ingress,dragonflydb-development"
