# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: delete-verdaccio-deployment
#   namespace: npm
#   annotations:
#     argocd.argoproj.io/hook: PostSync
#     argocd.argoproj.io/hook-delete-policy: HookSucceeded
# spec:
#   template:
#     spec:
#       containers:
#         - name: kubectl
#           image: bitnami/kubectl
#           command:
#             - /bin/sh
#             - -c
#             - |
#               echo "Deleting Verdaccio deployment..."
#               kubectl delete deployment verdaccio -n npm
#       restartPolicy: Never
