---
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-verdaccio-htpasswd
  namespace: npm
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: kubectl
          image: bitnami/kubectl
          command:
            - /bin/sh
            - -c
            - |
              echo "Deleting existing htpasswd secret..."
              kubectl delete secret verdaccio-htpasswd -n npm || true
              kubectl delete sealedsecret verdaccio-htpasswd -n npm || true
      restartPolicy: Never
