---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: verdaccio-deployment-manager-binding
  namespace: npm
subjects:
  - kind: ServiceAccount
    name: default
    namespace: npm
roleRef:
  kind: Role
  name: verdaccio-deployment-manager
  apiGroup: rbac.authorization.k8s.io
