---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: npm
  name: verdaccio-deployment-manager
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "delete"]
