---
apiVersion: v1
kind: Service
metadata:
  name: development-mongodb-0
  namespace: mongodb
spec:
  type: NodePort
  ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      nodePort: 32000
  selector:
    app: development-mongodb-svc
    statefulset.kubernetes.io/pod-name: development-mongodb-0
---
apiVersion: v1
kind: Service
metadata:
  name: development-mongodb-1
  namespace: mongodb
spec:
  type: NodePort
  ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      nodePort: 32001
  selector:
    app: development-mongodb-svc
    statefulset.kubernetes.io/pod-name: development-mongodb-1
---
apiVersion: v1
kind: Service
metadata:
  name: development-mongodb-2
  namespace: mongodb
spec:
  type: NodePort
  ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      nodePort: 32002
  selector:
    app: development-mongodb-svc
    statefulset.kubernetes.io/pod-name: development-mongodb-2
