apiVersion: batch/v1
kind: Job
metadata:
  name: patch-verdaccio-htpasswd
  namespace: npm
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: kubectl
          image: bitnami/kubectl
          command:
            - /bin/sh
            - -c
            - |
              kubectl patch secret verdaccio-htpasswd -n npm \
                -p '{"metadata": {"annotations": {"sealedsecrets.bitnami.com/managed": true }}}'
      restartPolicy: Never
