---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: npm
  name: verdaccio-secret-manager
rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "delete"
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    verbs:
      - "get"
      - "list"
      - "patch"
