---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: actions-runner
spec:
  encryptedData:
    github_token: AgBQ57cHT3pN3bkyBituwl2EDAK5R6PpMP4ouIAII8/nWNL6nZrTXIRt2MAKynlUArHI7hmkdy88kRqceFtsjRtHlVv8B5UCkiUYfug1Mbglmb27xCJT7ckL1sk0P47tDLHKM6cJeEgIw4gT8hynJalHBxHZLPjNZ03Hu8vXEMCs3dr3Obpqdt+r4FvxTi8DL/tPMBGLSkHfY1Jsf39r+eacmU2dTvGeiAnW6Sy1shpjQBk1kwXsNfRhM04SwBIrzgir76/MqrGiSMlG6ooxHy2aNiYMv+2w5h1CEOV1THhjf9YeZfi8IMRDzkphpR41g7RhhHOliGGPHe3e+evyKTWE+oqzeYsBHe42VGRhf8l5o+jtVW1r/DzwmSMAo+rfZRIUgRWxLqGz9QVKsM89XYwDlb+xbpSGk62fcFbwaiPzfadtuWr8oNYGGX4O7jIv/NCvAd05bXlwUpG2/Tle9kYCDPfYn9E0uWhtJPusPueqSriPyl2XFqPMrNsJoVmCe54khonGR3++C51EEfo5zo5so9VtU+J0qup2kSNkr640GIy9M0R8ciTwp5ffsDE+bXZeW8JrkuSZp9P7h93qTnyOoIq9YKWPnkjwZmJng46m4mnJve6wnDrpypEw7yqnYsths4qKKagjpNFNeE3IXkgd4NfTZ54G7LJPV5E5eZezLox0kwGFTL82uVBltBkv/y9M5Z3Z03PwT6xZvOUHOex4DIUtOzx49kjRJ7bPhg==
  template:
    metadata:
      creationTimestamp: null
      name: controller-manager
      namespace: actions-runner
    type: Opaque
