---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-internal
  namespace: registry
spec:
  isCA: false
  duration: 8760h
  renewBefore: 360h
  commonName: harbor-internal
  secretName: harbor-internal
  issuerRef:
    name: harbor-ca-issuer
    kind: Issuer
