apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-internal-ca
  namespace: postgres
spec:
  isCA: true
  duration: 8760h
  renewBefore: 360h
  commonName: "postgres-internal-ca"
  secretName: postgres-ca-bundle
  issuerRef:
    name: postgres-ca-issuer
    kind: ClusterIssuer
