---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-internal
  namespace: postgres-development
spec:
  isCA: false
  duration: 8760h
  renewBefore: 360h
  commonName: postgres-internal
  secretName: postgres-internal
  issuerRef:
    name: postgres-ca-issuer
    kind: Issuer
