---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: verdaccio-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "xplaceinmyheart.ru"
        - "*.xplaceinmyheart.ru"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "xplaceinmyheart.ru"
        - "*.xplaceinmyheart.ru"
      tls:
        mode: SIMPLE
        credentialName: xplaceinmyheart-ru-tls
