apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-internal-ca
  namespace: redis
spec:
  isCA: true
  duration: 8760h
  renewBefore: 360h
  commonName: "redis-internal-ca"
  secretName: redis-ca-bundle
  issuerRef:
    name: redis-ca-issuer
    kind: ClusterIssuer
