---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: redis-self-signed-issuer
  namespace: redis-development
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-root
  namespace: redis-development
spec:
  isCA: true
  duration: 8760h
  renewBefore: 360h
  commonName: redis-root
  secretName: redis-root
  issuerRef:
    name: redis-self-signed-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: redis-ca-issuer
  namespace: redis-development
spec:
  ca:
    secretName: redis-root