# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: redis
#   namespace: redis-development
# spec:
#   isCA: false
#   duration: 8760h
#   renewBefore: 360h
#   commonName: redis
#   secretName: redis
#   issuerRef:
#     name: redis-ca-issuer
#     kind: Issuer
#   keystores:
#     pkcs12:
#       create: true
#     cobinedPEM:
#       create: true
