---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: redis
  namespace: redis-development
spec:
  selector:
    istio: gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "redis.xplaceinmyheart.ru"

