---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: redis-selfsigned-issuer
  namespace: redis-development
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-ca-cert
  namespace: redis-development
spec:
  isCA: true
  duration: 8760h
  renewBefore: 730h
  commonName: "redis-ca"
  issuerRef:
    name: redis-selfsigned-issuer
  secretName: redis-ca-cert-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-tls
  namespace: redis-namespace
spec:
  isCA: false
  duration: 8760h
  renewBefore: 730h
  secretName: redis-tls-secret
  issuerRef:
    name: redis-ca-cert
    kind: Certificate
