---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: redis
spec:
  encryptedData:
    redis-password: AgASCPSyDzW2erckKHwEMRrRqRZ/ziuN1hRaUflqnuGYSgRzZ1Bv4bbXAy6DLV98clZ3ocgNAzk0FTh9XYGW/2x7MyAQXfCO8z5J11wAGYP/9yHf2eq7gHsl/oWNkO3vMsSXeQsyeehTmbkc7fKkE2CqDymR2+61Jmcih/jrLzOB8/H7+yEV8aLdttTdKQBnQI/T94c01f4kPE2QRAg+oQfUbiNfy2Kqb2xolaCuxTc6iNBhIh8GktnF0T9G9IJBz/KjB4byhkB88HNUhd8BDaVfnBc/S0WcRJfBOowKsQxqpDMIVexlnKcvlmZTcSWo2TxJ27FmVeKi2aGD0foAau91wdxx2ON6aUM2RogbOaSeWLP4VAV2n+xuXNbb/DgKHSwiHU3lPx6yPkh2RW5lXJX8ZO0J3qXjRpPkdu0gaUF1Y4HLLqV1TnLsWNmi1r7tOU2x9hOP+fM+T/EtTHMLQdioObLoBOaNw+1RAenvw6ZW1apXXNc0f1zDp7uUCh2ITWY/TGCskr74GxxCEsvwv1yQOt9fNexrEREro9Yh/QHI9OhU1ab4OZ0ktEdWAT/zmlBk2IvM79BWI9P4Lvdl2jXCHT4tAGAGgFMZbIHZ0EjeTAzAd61Xj61ALarIC88kB0Qvu8KqV2uE/80wvxE30uhhejjD2N5eMv45RDdF7cnKuqmCIig1WoYrTmz9CWKAVyX6zV5sMb5rz/pLVVbdN4rHq1BDto3mlMlA
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: redis
    type: Opaque
