---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: redis
spec:
  encryptedData:
    redis-password: AgCaAFcE76a/2zIF1ZQIqKd/iTk18VVO9uiekzFNQ4vcgw19jTps8GrmERBh27eZgyWus1EBVvDKSyo0hltYy0ja96pORzLhhA2BxVR63eA3I4Hl1QCgZqiUZKOIBzg5f55Z0zGNr6CdTMB393lleAuoydUYSzW/j1LNP6I+ptZ283sE1yWtW/uErDCpHFdZKnE7nD4AcvVooSWLZl7ZpgF2JnY366fD2OuQeG269Cx+oCjs6omgfP1QpfNZSLg8zRMAi9+W3BHvqlwK1W3cLXWjjx6NMdnKuCgTLWaXq84PeHkfstrPAJc14cLVcNcjhAC/0tCD/3B1CgHbeQfaMgUf1wky6QH7j+XFWJE7sgB4NBqVboMNiR4WOOCp8203+f2lF8SXbSYqRPblBXKLiITLnp/Jg46h2aPb8dQUUCiel2gZEKbDRBDESaHj52bJ4AMu40qUKFo400t6j39ZBt0lEl6DeCDxH2FaXrVJ34XmS7DvfAYxFseZgSCLWHw3fgvZW3RAFf0AuI+i4qRzSttUjMv+em01GH3WtcEzgh0VJr+PeyLy5eM1QbrQ3x6ynOYbRvHLODMFhlpcKtp/Re1neHYQ0Zb90xsI7jhi+6innt1HAqZ4XjJxhBh7INVIDIuzhBUH2Lwu2q9Scu5KYRb7bj6vndOgBuC16KaUnLwz98CBEFycMOmwfcDA1cr8mILox227PBxbvmEEx94fQOxBsyLluskSmMap
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: redis
    type: Opaque
