---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: redis
  namespace: redis-development
spec:
  hosts:
    - "redis.xplaceinmyheart.ru"
  gateways:
    - redis
  tls:
    - match:
        - port: 443
          sniHosts:
          - redis.xplaceinmyheart.ru
      route:
        - destination:
            host: redis-master
            port:
              number: 6379
