---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: redis
  namespace: redis-development
spec:
  hosts:
    - "redis.xplaceinmyheart.ru"
  gateways:
    - redis
  tcp:
    - match:
        - port: 6379
      route:
        - destination:
            host: redis-development-master
            port:
              number: 6379
