apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "s3.xplaceinmyheart.test"
        - "s3ui.xplaceinmyheart.test"
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "s3.xplaceinmyheart.test"
        - "s3ui.xplaceinmyheart.test"
      tls:
        mode: SIMPLE
        credentialName: xplaceinmyheart-ru-tls
