---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio
spec:
  encryptedData:
    root-password: AgAq49IL1O15Xi32fZ+FLlUnQ2fz2RVhsPJSL9RmpaUPKEUzhW8nJTb2ZRNoLGWO+iiR1c/p0KnnS+UZowjAhJIMPmO9t9XixruIEfVcBla9F7xwl7wDz/x1yh0M0gEQ7YKn8RRJaJZzHefI64l5KiC6x/4gvy2/tXDlBEdfZ3jtNtdxrRzDNBWMq/ic0Ch24Fmcj2NlX8CwFTfLOcygbACX5BFMgtirrwV5M2zXiamnE2vwUeYipcy8dQX2mYvD9mEh+3AXT5MSMzbbd8Mw/oGQqLUsDbaXaej2D1y5NYDPioekdbPdlXPlhIzSnHND5r26VRgEnHEZtYXAyuht5swHfaqXAcvLb3G916fWzoB2snoIhlzOn6GE6E51K83iuUwMxbkWzi2Tot0eSlhLaj36B67Vgao855znQm0JrLrobOdG1UFUv+MbSIsdItYvezzVAMSYKQTvlQm6yYHTqpQj/etdqPOt3HncNMNiJkkvLgFbSn7Mj0w1d9hH6UXmm3qSLLfH31Trmlox6Bq+6XHC5vRPNXfSx36Q9ba4UAVs59ApBYzrqd0SIkXEKnnfRn5yT6KTcE5d7Pow+TfWqyh2n1CaryZs0gikiBH/S0c14VJTFNI4W3u6bUTh4oQMbvRqEM7Ms0K6UqN1uMxYhkvoYLufLIjy8vOpbw6rd92BLgnWlGvANLvrMKfX4xk7ZI1KvBsS5Uu2JF2EfjQd/kGnMTnUHJ/O3l0=
    root-user: AgCMvRZyXUV2U9XK56RGUV4KctI/goorIbwkEpZHaeJpieqENt5h482C5LdKOwWGOEgB1pLZs3pmOnrGuwWdMZy1KqSGQAQhNIhnFtpACou2fMou0X/L4LtIrM0LUaN9keLhkOmYYSgjnjpjSTf83uN2Fw7iuw9oMPB17LwHOxr02kv+sYZK7AIEKnhzn4EUVV3vXkZACWjJkBW4eZiI2vEvli7msz4Lj15lwJ8pnpSCZormpp6U79b7OO+2E4v7wYdJEvf0azb5233jBsQcChoOioesyLAXHg5gJhIOg4ix489C+i6h3iHCVdv0iFh3miyVVqOh6s2t2AiEjCPJU/he25acPgut81znictX+LmR33gYU4oyCofsYn6lSpCzKLCsy9qRRZpDAcd8Gd1WmXskUzEcF79ej+tMWdsf3ND1QgrbOczuPD5AFZ9+Vb+5l9lt94+fSCbwqzQNa6Lm//m3l97j9Hy6g0RUl2l3xPajzkwP1FQv9cVGiN3O0xZ3pzJS6fy6a3Vdmiz0LlXvh0tu6IpfIOmdWCj8hnk3c/XUK68SlBCA5T/7W6N0jcXmbVqTuh+TdPC24ckdeowSy2CAbzFDYxG0PtIIcR4Wa9XrfEgieYKIdtcmaVJiQPOmUUarM0VYhbrf1Sm5kBB6zEBA4Gz3FwKiO59ajJQg8s0/kzctHlUI+KR/5dOysd88KJo9afN9B1I9KXL2zA==
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: minio
    type: Opaque
