---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio
spec:
  encryptedData:
    root-password: AgAC/KD3SQDdL2/bvP077bKmKinhVhNWVD8XbdU5OQGLvCSGu1+akGvqP6tJargZei972tlC57wudpdbcyyUT+F98CVlTQ/UHiuFDxiI4jb07jSQA0mQVtV+x/w5QOaXj18iHhyVN84JO8T3i19Ae1tmmpf7IFyrdo6gytSCs6K838Gel2rme0RAzvRXWeM+XY/Nz3gSsTkf8AAQ2l+UaHqmSogfoU0wbgY4ZEKjHpayKMFtiU95PsEr1pg0ix2BlSg64tubzAwkoN+tDY98LVc/VlFURlZ6t5b3g2ZGXMi8/tfKBpymeZWeHSIZPtt5fr6RrptjkBRng4PrlU5gd/T8mX4dm0Tuh8wjooWjx1RUB08x6x2ewvYX1Tj4qPnIH/61b9sT7OJmJYXwe0oV7zOe/CijjchcTwbVakDF+fTUXCupDagJDbKCya0ltaefBCz7kKYHXhBn7gi2fnjgmUbfthh/jG1VlDiT2jgd/pAIcdAsZA9+pNV4DGIC2qU8Yot9vVUvvyGWltAENLf4OVKXtnpPSs6dXtQyH+wbz7zXzIYflluUNYZHaQRRIJdmQJ5J4vXI+20BozJh6yQPeLMEBPXy70bmWDTyS9gxKUynoSNf6j1avRJpBFI3054QYdwV+ww0EsFt6y5fY3hlLTyjbOBrtbiieRNhP2UYeQo2fjDFVd+dbevNAs4wHYPlPikCd2wZHmMnsSeN7GNqb6lER5ROKo+xAcM=
    root-user: AgBm2Iiu3h21KSpqaftHFWRAIhjHq3h2HRkgrcTSZUv3Ugztc+iRmLxisPrq1cVf90i9K1WJIIaXJ8EkC6/a5HPuHVMvU8dhDwdtky6Q9fu6/lggyYAdP8lP4UxbnPGu6ZZ9J7Xks9efw4NdaJ6n1rTYLFl3MAB8kjE6OO8ePxel75BtifdjHLv84afvfSqBaTIQ70oJv+idp95YtTHj8w0WIQfeFlb+L69gWPslr12pq5KKDg5g6kQ8qs9WU/ALMVMIna/cqxDFnyHqUZin0gnAGr6wsSptkjxXOLn5bXBVDtUxTZYO9zRp1CI8meWZkkdiNCxIyn3Sezh2NEwi0ANYTN/yao0Z8zvgdme88l0/vObFeN0NRu5JqlzkqCtpUSycuhlZZN9ecYmODNbyHERIDHf5s7a7yyOik7q/MtMqHmQOqFRa7KazPV1rXWtrAB5HxEdg76Q2sk1bTKY43ClWb6wOJBIsBOmd5m0mkPYC/7RmYhR/EsMvALU3t2fEgy6Gwo9BA40mbFzwJYcCTshRM6I2xnhjE6C0zQw0SuUxJSf+wZUL3FMsKhOgDFx7CpWElPIJ9q3Ee5U+Wonoq/3cnJyJSaHXhxz+TYYUrii4gqEnxN/ua5Foum+as3CrYzY3VlSIr0bGBYIPbuWT6VyUi8doFZJxYvuPwp4svegnYPhZmrOqYNd2tXJHlxLb1DICaFHMTYkDYzZYnxU=
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: minio
    type: Opaque
