---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio
spec:
  encryptedData:
    PASSWORD: AgBnOFEBm7SHuoNS1HXm2affihdL3mm+VXD0/JNVFrcWLgH0EHqXHGnnmXROjFKFEKOqPtZ6h224fT2HK52FB+fpqMyB7tW8BbYIUUpmYsRt5SaS5Wqg8/tB7gx5eLqCM7w7E9PV+GGd4vSpLK5bhp/P1XjKsUb/+0Pgh6Gjhjfssu6hGBiz2mnXjek9tkO1yn/kKRCBu3iksTzWIsP0WvhWegNV4J941pmIy/B5ajwuJT4hXFudX0Rw4El3bu/ruEQkN4Vp/RN1cl6NYctsSiTaPXxxYbwP6NzfDpCO5AOs19oJxYRGYB09kpWZdhU1oCG1g+x3Os7zFlCHI8Rn3MxGFs07u8KDqYtkbGZTvNuNPytqqiNgn5se9ZXGgRfvWCbaXgOrgbPralQtV4SZ4bAWZNrL2IxNKrzEFDYxLD4IerM3Gwvdp/IhYSS8ThW2CardiaPA9c76/bsIE5Beo9cCg4evC+mHb4xdr9T/mIiPa3Sr6nbRdhqaFH72pg4Sj83H8sSbBkoX2U0SdcT2/BjVl61kJ1n23O1XaoaTBmNc6MYdi4A2LMuTi1OxoVljdxrsoZWCWNgNVhaYJe256sSFQ2ufAiw/TSstvjVshYosHgm/PnkWa2YVmYn4/6mbTw37Zwv2ZGPxrxDwi+2UGKFdqMbE3FAkkx0Il+qtFqhRXT+olG6vC+j+uOO0DRrBV4PVercU82XkSBV8/RcClHUBPvy43HB7EmK3
    USER: AgB/GPOdbEHbyaljZ6Mtq2c9fY/TGok+aRmY6bOdS8otGWcVAwYAh6BsvMJb6jM8O9KENmcCWwA0KIuXhqDu6anaHImMQFOtmGOBmJbhb06H4Aawv83xRnoln7q2zl0zqTa46UpYBGRvLPGFJ5C7Ed1qxCgCN2JwxpdXr/E++wB9w3lbJIWpTqVGhnfOB0QHispLyl8tBdexlyETkQL9edf+cT6EYoHh9QnmwEot1ox6vuwycEGNDbPOoqmAQw4O7jzQOtbJVXUiLpQimo4an1cnSbNeLofFJdMRUBeprncOXUe3ey2VaeQKTGReD4SL3jK/bBn7XikPZTS09OZkZTKzAExeb4mj0LUeU07YUFG0Xs0d0AGfbSwqYmmOjaMI8H22IKT+we3FDgZbKNh3kycTtJKdCVEo2VQdJfG4c/hxcYYBFCGFMlkrQ5NMTuED5OMeqZdziW0wcPqkLy1hIY/m3xGEtpvCWwltN+KIWUj27MUm2pVvkVzO1XHGauy5NA99yP1L0rFKh9m+3UsBz4U9zyDfcjZXp/uI2ImUNTzSJSj3pmPK8Kbm4BAswC4X+DBDmwssyMJ6QQoBKs0/3E3CUm8byMfHsXMtt9HAkJTXfupI2ViLrDcyDNO4Q6ganeGLmD0CfOmZIB9gL4kcqfL5jhy/sNmidx7f+EqS4uYlIc4apURX0eecYzIUGmNiQDmVkQIJwKQUwLmbJSg=
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: minio
    type: Opaque
