---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio
spec:
  encryptedData:
    PASSWORD: AgAh/BzynmTZ6quHMAh3LEVOUISAaw0jqZ0MWKIXEw313ovD8DIe5DpWd3im70Yt9WIM9JHwa+CVre7guHfOX0bMvhrUpKtogmFYtWisJkRDuBNZA0SD4bHsLRN7ZOArQeSCA4b0cZyRRQextqhugOf2AQ0RNH32nfbrJJmPI4RUXf9luM9PzhFgNwDtv18y/SPYnHK6edBl1owusOo+V9ODzpN2Urk0N8r8lYh6TJCFnJ9IU/nxIhE/czMmtGPCUjEcRy9wNPMgxnydj8TDmjr+RT0ufGjopaCWX8y6+MbIs1HQ1tAIDx/uJldkiVTlgj7b5d37gHfQliXj0spOmDGmqEmjFKpHx/KGRxRadw7i0tAwmLzDvyXLwXa7/aFHK1T/ycp21LpsSSJazNvsXK17MkKPnWDX91H8MemkYrsMtNPiNHBqym/A61ScEm5I4vmCiX4uywJ5DXEkXxYT3nfBkMqC8iHAzaTTwzn4prMH7ZGB63vKe8VO5GLWzs1jDG6L8bIRjUftiDFGBZEuDE2CrQc6TnZw7bE8CT5j9+byj9NyKuAjdlvu9AA+Ofrbq5PyX0Z/f72r1pp39baDZsMwjSTdwtei3J89rfyC3H4MpaTtx2c+i7WSWiJFnbsgz1ScidHTe1C8hu3a7Zekq9SAoDJV0CzvFL0CnLmvHuxFu0VDYSpb1cc7pBNMA5B6dg25uJon+4H/WGRGxPClJZAgRXJ8Z2jIo1st
    USER: AgAXrQEoC2EhC+JOI8kKgk/JEOnqbyAlFB/J8HuTm7La8lMsUhUm+tk35XhexACeV7OnRRj4M9E9UuigFhOBN9wGjHg1E7hWDfMMzqTr33EV3gbOLAxMzaH9D5KcuhKjEGTH1HjZkHag+xzTMQUrOFJvaMaQL+s1SMMF0iU/+nRrwNIFglzOAyoDOForQ79VO/NEyEwc75TJYytax5nB1MGhlADIm7mbH90x+L76p0z6TIhMlbTlds/nkh4PUJ9EF9F9pmyiLxoxDWHzuyCWym9J/dfelP+cUICWuZqiLgzQXgZ6E7A0gbuI4Sz2De/pVBAar/pztuV/t8BlNcuT3FqnO8htlESNDMJ0WufYCN3eMYsluiBDRT0DWOwuWT/txzhalsd3QIBKfEp3HjJXuckMHIDCxqbedP7E+VVGguZluQz2jk99E1Xxn0PqqIVSoEbT+9VLYSfkUWCi/hXnNu+N/zs5O6eJi8otD6D4xn6K9jtWawq6rCPO504NolMLtFKbNe0rMWmu0mvjA33MUwFhITgyR1XGTA+kREr8R3759evvbuu2SQnWLR2hTxveQGEsYKGiy1uekjSKn6AiVwDbOXXoBFJrECZ45qAhKsbfvqyW1PShuMqeSKUmOkL19yPPzt7aYOm4s9fLOT+uCrxO4W/6Jp9xsc7jN7xPntPgJkrB5FBJXZxQ2+OZh3+wSCPrRtO1ECiA2t3cdfY=
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: minio
    type: Opaque
