---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dragonflydb-development
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/dragonflydb/dragonfly/helm/dragonfly
      chart: dragonfly
      targetRevision: 1.25.1
      helm:
        valueFiles:
          - $values/values/dragonflydb.yaml
    - repoURL: https://github.com/WapogaozeF/xplace-infra.git
      ref: values
      targetRevision: HEAD
    - repoURL: https://github.com/WapogaozeF/xplace-infra.git
      path: manifests/dragonflydb
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: dragonflydb-development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
