---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: harbor
      targetRevision: 24.0.2
      helm:
        valueFiles:
          - $values/values/harbor.yaml
    - repoURL: https://github.com/WapogaozeF/xplace-infra.git
      ref: values
      targetRevision: HEAD
    # - repoURL: https://github.com/WapogaozeF/xplace-infra.git
    #   path: manifests/registry
    #   targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
