---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: verdaccio-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/WapogaozeF/xplace-infra.git
      path: manifests/verdaccio-secret
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: npm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Replace=true
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
