---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: verdaccio-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/WapogaozeF/xplace-infra.git
      path: manifests/verdaccio-secret
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: npm
  hooks:
    - name: delete-verdaccio-deployment
      kind: Pod
      type: PreSync
      deletePolicy: HookSucceeded
      action: delete
      pod:
        name: verdaccio-secret-name
        namespace: npm
        spec:
          containers:
            - name: delete-verdaccio-secret
              image: alpine
              command: ["sh", "-c"]
              args: ["kubectl delete secret verdaccio-htpasswd -n npm"]
    - name: delete-verdaccio-deployment
      kind: Pod
      type: PostSync
      deletePolicy: HookSucceeded
      action: delete
      pod:
        name: verdaccio-pod-name
        namespace: npm
        spec:
          containers:
            - name: delete-verdaccio-pod
              image: alpine
              command: ["sh", "-c"]
              args: ["kubectl delete deployment verdaccio -n npm"]
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Replace=true
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
